# itk-version: 1.0.0

version: "3"

services:
  phpfpm:
    image: itkdev/php8.1-fpm:latest
    environment:
      - PHP_XDEBUG_MODE=${PHP_XDEBUG_MODE:-off}
      - PHP_MAX_EXECUTION_TIME=30
      - COMPOSER_VERSION=2
      - DOCKER_HOST_DOMAIN=${COMPOSE_DOMAIN}
      - PHP_IDE_CONFIG=serverName=localhost
    volumes:
      - .:/app:delegated
