on:
  push:
    tags:
      - '*.*.*'

name: Create Github Release

permissions:
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    env:
      COMPOSER_ALLOW_SUPERUSER: 1
      APP_ENV: prod
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create a release in GitHub
        run: gh release create ${{ github.ref_name }} --verify-tag --generate-notes
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}
        shell: bash
