name: PHP Code Sniffer

env:
  COMPOSE_USER: runner

on:
  pull_request:
  push:
    branches:
      - main
      - develop

jobs:
  coding-standards:
    name: PHPCS - Check Coding Standards
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Create docker network
        run: |
          docker network create frontend

      - run: |
          docker compose run --rm phpfpm composer install
          docker compose run --rm phpfpm vendor/bin/phpcs --standard=phpcs.xml.dist
